version: 2

jobs:
    build:
        docker:
            - image: gallileo/radarr-cci-primary:4.8.1
        steps:
            - checkout
            - run: git submodule update --init --recursive
            - run:
                name: Clean Build
                command: ./build.sh Clean
            - run:
                name: Restore Nuget
                command: ./build.sh NugetMono
            - run:
                name: Build
                command: ./build.sh Build
            - run:
                name: Gulp
                command: ./build.sh Gulp
            - run:
                name: Package
                command: ./build.sh Package
            - run:
                name: Preparing Tests
                command: mkdir _tests/reports
            - run:
                name: Test mediainfo
                command: wget https://mediaarea.net/repo/deb/repo-mediaarea_1.0-5_all.deb && dpkg -i repo-mediaarea_1.0-5_all.deb && apt-get update && apt-get install -y mediainfo && mediainfo _tests/Files/Media/H264_sample.mp4
            - run:
                name: Unit Tests
                command: ./test.sh Linux Unit
            - run:
                name: Integration Tests
                command: ./test.sh Linux Integration
            - store_test_results:
                path: _tests/reports/
            - store_artifacts:
                path: _output
            - store_artifacts:
                path: _output_mono
            - store_artifacts:
                path: _output_osx
            - store_artifacts:
                path: _output_osx_app
